name: Upload and download single file
on: push
jobs:
  upload_file:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > file.txt
      - uses: actions/upload-artifact@v1
        with:
          name: file
          path: file.txt
  download_file:
    name: Download File
    runs-on: ubuntu-latest
    needs: upload_file
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: file
      - run: cat file.txt
